### ISSUE TITLE
sh

### ISSUE THREAD

**Issue by blaggacao** [acsone/git-autoshare#12] opened 2019-12-19 05:05 UTC
https://github.com/acsone/git-autoshare/blob/640fe37e620e90a27284024a801f4352fb0fc7f7/git_autoshare/core.py#L44

```python
from sh import git
```

**Comment by Yajo** [comment] 2020-04-22 09:40
Duplicate of #1

**Comment by sbidoul** [comment] 2020-04-22 09:56
Yes, let's close this one.

**Closed by sbidoul** 2020-04-22 09:56 UTC
